runtime: python312

instance_class: B1

handlers:
  - url: /static
    static_dir: staticfiles/
    secure: always

  - url: /.*
    script: auto
    secure: always

env_variables:
  DJANGO_SETTINGS_MODULE: "sistema.settings"
  DEBUG: "True"

entrypoint: gunicorn sistema.wsgi:application --bind 0.0.0.0:$PORT

manual_scaling:
  instances: 1